In [6]:
import torch
import numpy as np

In [2]:
torch.__version__

'1.2.0'

In [3]:
torch.cuda.is_available()

False

In [8]:
# Tensors in PyTorch are represented using the torch.Tensor class
t = torch.Tensor()
type(t)

torch.Tensor

In [9]:
#Tensor attributes
print(t.dtype)

torch.float32


In [10]:
print(t.device)

cpu


In [11]:
print(t.layout)

torch.strided


In [13]:
device = torch.device('cuda:0')
device

device(type='cuda', index=0)

In [29]:
## Tensor computations depend on the device and the type

t1 = torch.tensor([1,2,3])
t2 = torch.tensor([1.,2.,3.])

In [30]:
t1.dtype

torch.int64

In [31]:
t2.dtype

torch.float32

In [32]:
t1+t2

RuntimeError: expected device cpu and dtype Float but got device cpu and dtype Long

In [33]:
t1 = torch.tensor([1,2,3])
t2 = t1.cuda()

AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx

In [34]:
data = np.array([1,2,3])
type(data)

numpy.ndarray

In [35]:
##Creating torch tensors
# using Tensor class constructor -> notice change in datatype
torch.Tensor(data)

tensor([1., 2., 3.])

In [36]:
# using tensor factory function
torch.tensor(data)

tensor([1, 2, 3], dtype=torch.int32)

In [37]:
# using as_tensor()
torch.as_tensor(data)

tensor([1, 2, 3], dtype=torch.int32)

In [38]:
# using from_numpy
torch.from_numpy(data)

tensor([1, 2, 3], dtype=torch.int32)

In [39]:
## Tensor creations without data
##identity tensor creation
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [40]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [41]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [42]:
torch.rand(2,2)

tensor([[0.6449, 0.5865],
        [0.7917, 0.3923]])

In [45]:
## Creating pytorch tensors - Best Option

data = np.array([1,2,3])

In [48]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [49]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)


In [50]:
print(t1.dtype)
print(t2.dtype)
print(t3.dtype)
print(t4.dtype)

torch.float32
torch.int32
torch.int32
torch.int32


In [52]:
torch.get_default_dtype() # hence torch.Tensor() class construction function is returning float dtype by default

torch.float32

In [53]:
## factory functions like torch.tensor(), torch.as_tensor(), torch.from_numpy() infer datatype from the incoming data
torch.tensor(np.array([1,2,3]))


tensor([1, 2, 3], dtype=torch.int32)

In [54]:
torch.tensor(np.array([1.,2.,3.]))

tensor([1., 2., 3.], dtype=torch.float64)

In [55]:
torch.tensor(np.array([1,2,3]), dtype = torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [56]:
## If we change the values of numpy array

data[0] = 0
data[1]= 0
data[2] = 0


In [57]:
# tensors created using torch.Tensor() and torch.tensor() creates a copy of input data in memory
print(t1)
print(t2)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)


In [58]:
# shares memory with input data 
print(t3)
print(t4)

tensor([0, 0, 0], dtype=torch.int32)
tensor([0, 0, 0], dtype=torch.int32)


best method to go for is torch.tensor() factory function ..
for memory optimization, torch.as_tensor() factory function over from_numpy() because as_tensor() accept any python array and not necessarily numpy array


## Flatten , reshape and squeeze
## Tensor operation types
1. Reshaping
2. Element wise operation
3. Reduction operation
4. Access operation

# Reshaping 

In [60]:
t = torch.tensor([[1,1,1,1],
                [2,2,2,2],
                [3,3,3,3]
                 ], dtype = torch.float32)

In [62]:
t.size()

torch.Size([3, 4])

In [63]:
t.shape

torch.Size([3, 4])

In [65]:
# to view the rank of the tensor
len(t.shape)

2

In [66]:
torch.tensor(t.shape).prod()

tensor(12)

In [68]:
# number of elements
t.numel()

12

In [69]:
t.reshape([2,6])

tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])

In [70]:
t.reshape(1,12)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [71]:
t.reshape(4,3)

tensor([[1., 1., 1.],
        [1., 2., 2.],
        [2., 2., 3.],
        [3., 3., 3.]])

In [72]:
t.reshape(12,1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.]])

In [73]:
print(t.reshape(1,12))
print(t.reshape(1,12).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [76]:
print(t.reshape(1,12).squeeze())
print(t.reshape(1,12).squeeze().shape)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])


In [81]:
print(t.reshape(1,12).squeeze().unsqueeze(dim=0))
print(t.reshape(1,12).squeeze().unsqueeze(dim=0).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [83]:
def flatten(t):
    t = t.reshape(1,-1)
    t = t.squeeze()
    return t

In [84]:
flatten(t) # reshape and squeeze

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [86]:
t.reshape(1,12) # only reshape

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [87]:
t1 = torch.tensor([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
])
t2 = torch.tensor([
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2]
])
t3 = torch.tensor([
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3]
])

In [88]:
t = torch.stack((t1,t2,t3))

In [89]:
t

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]])

In [90]:
t.shape

torch.Size([3, 3, 4])

In [91]:
t = t.reshape(3,1,3,4)

In [93]:
t.shape

torch.Size([3, 1, 3, 4])

In [94]:
t[0]

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])

In [95]:
t[0][0]

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [96]:
t[0][0][0]

tensor([1, 1, 1, 1])

In [97]:
t[0][0][0][0]

tensor(1)

In [100]:
t.reshape(1,-1)[0]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [102]:
t.reshape(-1)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [103]:
t.view(t.numel())

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [104]:
t.flatten()

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [105]:
t.flatten(start_dim=1).shape

torch.Size([3, 12])

In [106]:
t.flatten(start_dim=1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [108]:
t.reshape(3,-1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

# Element wise operation or Component wise or Point wise
Element wise operation is an operation between two tensors that operates on corresponding elements within the respective tensors.

In [109]:
t1 = torch.tensor([
    [1,2],
    [3,4]
], dtype = torch.float32)

t2 = torch.tensor([
    [9,8],
    [7,6]
], dtype = torch.float32)

In [110]:
t1[0] # elements from first axis is array

tensor([1., 2.])

In [111]:
t1[0][0] # elements from second axis is number

tensor(1.)

In [112]:
t2[0][0]

tensor(9.)

In [113]:
t1 + t2

tensor([[10., 10.],
        [10., 10.]])

In [114]:
t1 - t2

tensor([[-8., -6.],
        [-4., -2.]])

In [115]:
t1 + 2

tensor([[3., 4.],
        [5., 6.]])

In [116]:
 t1/2

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

In [117]:
t1 * 2

tensor([[2., 4.],
        [6., 8.]])

In [118]:
t1.mul(2)

tensor([[2., 4.],
        [6., 8.]])

In [119]:
t1.add(2)

tensor([[3., 4.],
        [5., 6.]])

In [120]:
t1.sub(2)

tensor([[-1.,  0.],
        [ 1.,  2.]])

In [121]:
t1.div(2)

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

In [122]:
np.broadcast_to(2,t1.shape)

array([[2, 2],
       [2, 2]])

In [123]:
t1 + 2

tensor([[3., 4.],
        [5., 6.]])

In [124]:
t1 + torch.tensor(np.broadcast_to(2, t1.shape), dtype = torch.float32)

tensor([[3., 4.],
        [5., 6.]])

In [127]:
t1 = torch.tensor([
    [1,1],
    [1,1]
], dtype = torch.float32)
t2 = torch.tensor([2,2], dtype = torch.float32)

In [128]:
t1 + t2

tensor([[3., 3.],
        [3., 3.]])

In [129]:
t = torch.tensor([
    [0,1,2],
    [3,4,5],
    [6,7,8]
], dtype = torch.float32)

In [130]:
t.eq(0)

tensor([[ True, False, False],
        [False, False, False],
        [False, False, False]])

In [131]:
t.le(7)

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True, False]])

In [137]:
t.ge(5)

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])

In [132]:
t <= torch.tensor(
    np.broadcast_to(7, t.shape),
    dtype = torch.float32
)

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True, False]])

In [133]:
t.abs()

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])

In [134]:
t.sqrt()


tensor([[0.0000, 1.0000, 1.4142],
        [1.7321, 2.0000, 2.2361],
        [2.4495, 2.6458, 2.8284]])

In [135]:
t.neg()

tensor([[-0., -1., -2.],
        [-3., -4., -5.],
        [-6., -7., -8.]])

# Tensor Reduction operation
A reduction operation on a tensor is an operation that reduces the number of elements contained within the tensor.

In [138]:
t = torch.tensor([
    [0,1,0],
    [2,0,2],
    [0,3,0]
], dtype = torch.float32)

In [139]:
t.sum()

tensor(8.)

In [140]:
t.numel()

9

In [141]:
t.sum().numel()

1

In [142]:
t.sum().numel() < t.numel()

True

In [143]:
t.sum()

tensor(8.)

In [144]:
t.prod()

tensor(0.)

In [145]:
t.mean()

tensor(0.8889)

In [146]:
t.std()

tensor(1.1667)

In [147]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2,],
    [3,3,3,3]
], dtype = torch.float32)

In [148]:
t.sum(dim=0)

tensor([6., 6., 6., 6.])

In [149]:
t.sum(dim=1)

tensor([ 4.,  8., 12.])

In [156]:
# Argmax tensor reduction operation -> tells index location of maximum value of the tensor
t = torch.tensor([
    [1,0,2],
     [3,4,5],
     [6,12,7]
])

In [157]:
t.max()

tensor(12)

In [158]:
t.argmax()

tensor(7)

In [159]:
t.flatten()

tensor([ 1,  0,  2,  3,  4,  5,  6, 12,  7])

In [160]:
t.max(dim=0)

torch.return_types.max(values=tensor([ 6, 12,  7]), indices=tensor([2, 2, 2]))

In [161]:
t.max(dim=1)

torch.return_types.max(values=tensor([ 2,  5, 12]), indices=tensor([2, 2, 1]))

In [162]:
t

tensor([[ 1,  0,  2],
        [ 3,  4,  5],
        [ 6, 12,  7]])

In [163]:
t.argmax(dim=0)

tensor([2, 2, 2])

In [164]:
t.argmax(dim=1)

tensor([2, 2, 1])

In [170]:
t = torch.tensor([
    [1,2,3],
    [2,3,4]
], dtype = torch.float32)

In [171]:
t.mean()

tensor(2.5000)

In [172]:
t.mean().item()

2.5

In [173]:
t.mean(dim=0).tolist()

[1.5, 2.5, 3.5]

In [178]:
t.mean(dim=1).numpy()

array([ 2.,  3.], dtype=float32)